logicalclocks/kagent-chef

templates/default/agent.py.erb
=> remove spark from kagent

.kitchen.yml, attributes/default.rb, metadata.rb, providers/config.rb, providers/tf.rb, recipes/default.rb, recipes/install.rb, resources/config.rb, resources/tf.rb, templates/default/agent.py.erb, templates/default/config.ini.erb, templates/default/csr.py.erb, templates/default/kagent.erb, templates/default/shutdown-all-local-services.sh.erb, templates/default/start-all-local-services.sh.erb
Early work for serving and getting logs for tensorflow jobs.
=> Tensorflow

libraries/default.rb, templates/default/conda.sh.erb
Remove by library name, not libraryname=version.
=> Fix conda remove libs

templates/default/config.ini.erb
change host-id from ip to hostname as it is needed by influxdb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-74
=> HOPSWORKS-74

recipes/dev.rb, templates/default/iptables.rules.erb
Forward mysqld port with iptables
https://hopshadoop.atlassian.net/browse/HOPSWORKS-81
=> HOPSWORKS-81

templates/default/agent.py.erb
Truncate the return message of a failed command
https://hopshadoop.atlassian.net/browse/HOPSWORKS-161
=> HOPSWORKS-161

recipes/install.rb
COmment out installation of cherrypy-wsgiserver
=> COmment out installation of cherrypy-wsgiserver

providers/keys.rb, templates/default/anaconda_env.sh.erb
Account for antonios' changews.
=> fix signing certificates

files/default/rsyslog.ubuntu, files/default/syslog.centos, recipes/install.rb
Update logrotate policies for /var/log/messages log file
=> Update logrotate policies

attributes/default.rb, metadata.rb, providers/config.rb, providers/param.rb, recipes/default.rb, recipes/install.rb, templates/default/agent.py.erb, templates/default/anaconda_env.sh.erb, templates/default/anaconda_sync.sh.erb, templates/default/shutdown-all-local-services.sh.erb, templates/default/start-all-local-services.sh.erb, templates/default/status-all-local-services.sh.erb
https://github.com/hopshadoop/hops-testing/pull/20
=> HOPSWORKS-382

attributes/default.rb, providers/keys.rb, recipes/default.rb, recipes/install.rb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-445
=> Downloader for karamel

templates/default/agent.py.erb, templates/default/anaconda_env.sh.erb, templates/default/conda.sh.erb
HOPSWORKS-412 pip-support and conda fixes
=> HOPSWORKS-412 pip-support and conda fixes

providers/keys.rb, templates/default/csr.py.erb
[HOPSWORKS-455]  Refactor csr.py script
[HOPSWORKS-455]  Add initialize parameter to csr provider
[HOPSWORKS-455]  Fix bug with variables and parse logging level from config
https://hopshadoop.atlassian.net/browse/HOPSWORKS-455
=> [HOPSWORKS-455]  Refactor csr.py script

templates/default/agent.py.erb
[HOPSWORKS-460]  Process new commands protocol
[HOPSWORKS-460]  Extend heartbeat protocol
[HOPSWORKS-460]  Fix bug in OPs handling
https://hopshadoop.atlassian.net/browse/HOPSWORKS-460
To update the agent, download the patch file from the JIRA above and `patch /srv/hops/kagent/agent.py < agent-0.5.0.patch`
=> [HOPSWORKS-460]  Extend heartbeat protocol

templates/default/agent.py.erb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-475
=> [HOPSWORKS-475]  Miscalculated memory usage

attributes/default.rb, recipes/install.rb, templates/default/agent.py.erb, templates/default/config.ini.erb, templates/default/csr.py.erb, templates/default/sudoers.erb
[HOPSWORKS-454]  Add handling for system commands
[HOPSWORKS-454]  Add attribute in kagent config for service rotate endpoint
[HOPSWORKS-454]  Implement key rotation
[HOPSWORKS-454]  Rotate key from kagent
[HOPSWORKS-454]  Fix log level
[HOPSWORKS-454]  Bug fixes
[HOPSWORKS-454]  Call csr.py script directly instead of using the classes because of permission errors on the certificate files
https://hopshadoop.atlassian.net/browse/HOPSWORKS-454
=> [HOPSWORKS-454]  Service certificate rotation

recipes/install.rb, templates/default/agent.py.erb
[HOPSWORKS-461]  Add Conda commands handler
[HOPSWORKS-461]  Async handling of system commands
[HOPSWORKS-461]  Fix Conda commands async execution
[HOPSWORKS-461]  Fix deletion of successfully sent commands status
[HOPSWORKS-461]  Add missing comma
[HOPSWORKS-461]  Fix bug with libOp command and remove reduntant code
Dependent on PR https://github.com/hopshadoop/hopsworks/pull/887
https://hopshadoop.atlassian.net/browse/HOPSWORKS-461
=> [HOPSWORKS-461] Remove the execution of commands from the Heartbeat loop

templates/default/agent.py.erb
[HOPSWORKS-485]  Fix problem with concurrent libOps for the same project
[HOPSWORKS-485]  Fix case where status for the same command has changed during heartbeating
=> [HOPSWORKS-485] Fix bug with kagent Heartbeating commands status

attributes/default.rb, templates/default/anaconda_env.sh.erb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-522
This also adds Azure's Spark MML library to the set of installed pip libraries when you create an anaconda environment.
=> [HOPSWORKS-522] - TensorFlow upgrade 1.7

metadata.rb, recipes/default.rb
This PR is to backport @robzor92's fix for the cheroot install to the branch 0.4
=> Backport fix for cheroot import in agent.py

attributes/default.rb, libraries/default.rb, metadata.rb, recipes/default.rb, templates/default/agent.py.erb, templates/default/anaconda_env.sh.erb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-587
=> [HOPSWORKS-587] Chef recipe bugfixes for upgrading

files/default/csr.py, files/default/kagent_utils/kagent_utils/__init__.py, files/default/kagent_utils/kagent_utils/file_state_store.py, files/default/kagent_utils/kagent_utils/kagent_config.py, files/default/kagent_utils/kagent_utils/none_state_store.py, files/default/kagent_utils/kagent_utils/state_store.py, files/default/kagent_utils/kagent_utils/state_store_exceptions.py, files/default/kagent_utils/kagent_utils/state_store_factory.py, files/default/kagent_utils/tests/test_file_state_store.py, files/default/kagent_utils/tests/test_kagent_config.py, files/default/kagent_utils/tests/test_state_store_factory.py, templates/default/config.ini.erb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-595
[HOPSWORKS-595]  Fix bugs
[HOPSWORKS-595]  Lock state store operations
[HOPSWORKS-595]  Add layout version for recovered states
[HOPSWORKS-595]  Move state store to kagent-utils package
[HOPSWORKS-595]  Testing for state store
[HOPSWORKS-595]  Format state store
=> [HOPSWORKS-595]  Introduce state store for agent

templates/default/config.ini.erb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-614
=> [HOPSWORKS-614]  Be consistent on config.ini separators

attributes/default.rb
java8 use current latest build 181 as default
=> [Hopsworks-621]

attributes/default.rb, providers/keys.rb, recipes/install.rb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-627
=> [HOPSWORKS-627] change kagent user to a system user

recipes/install.rb, templates/default/anaconda_env.sh.erb, templates/default/anaconda_sync.sh.erb, templates/default/conda.sh.erb, templates/default/get-pid.sh.erb, templates/default/keystore.sh.erb, templates/default/restart-agent.sh.erb, templates/default/restart-service.sh.erb, templates/default/shutdown-all-local-services.sh.erb, templates/default/start-agent.sh.erb, templates/default/start-all-local-services.sh.erb, templates/default/start-service.sh.erb, templates/default/status-all-local-services.sh.erb, templates/default/status-service.sh.erb, templates/default/stop-agent.sh.erb, templates/default/stop-service.sh.erb
https://hopshadoop.atlassian.net/browse/HOPSWORKS-623
=> [HOPSWORKS-623]  Sanitize bash scripts

.gitignore, attributes/default.rb, files/default/agent.py, files/default/kagent_utils/kagent_utils/__init__.py, files/default/kagent_utils/kagent_utils/circular_linked_list.py, files/default/kagent_utils/kagent_utils/concurrent_circular_linked_list.py, files/default/kagent_utils/kagent_utils/conda_envs_watcher_action.py, files/default/kagent_utils/kagent_utils/interval_parser.py, files/default/kagent_utils/kagent_utils/interval_parser_exceptions.py, files/default/kagent_utils/kagent_utils/kagent_config.py, files/default/kagent_utils/kagent_utils/watcher.py, files/default/kagent_utils/kagent_utils/watcher_action.py, files/default/kagent_utils/setup.cfg, files/default/kagent_utils/setup.py, files/default/kagent_utils/tests/test_circular_linked_list.py, files/default/kagent_utils/tests/test_conda_envs_watcher_action.py, files/default/kagent_utils/tests/test_interval_parser.py, files/default/kagent_utils/tests/test_kagent_config.py, files/default/kagent_utils/tests/test_watcher.py, metadata.rb, recipes/install.rb, templates/default/config.ini.erb
Garbage collect unused Anaconda environments
https://logicalclocks.atlassian.net/browse/HOPSWORKS-648
=> [HOPSWORKS-648] Conda environments GC

files/default/kagent_utils/kagent_utils/kagent_config.py, recipes/default.rb, templates/default/keystore.sh.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-582
=> [HOPSWORKS-582]  Change to FQDN

files/default/kagent_utils/kagent_utils/conda_envs_watcher_action.py, files/default/kagent_utils/kagent_utils/kagent_config.py, files/default/kagent_utils/setup.py, files/default/kagent_utils/tests/test_conda_envs_watcher_action.py, files/default/kagent_utils/tests/test_kagent_config.py, recipes/default.rb, templates/default/config.ini.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-725
=> [HOPSWORKS-725] Generalize blacklisted anaconda environments for kagent

recipes/anaconda.rb, recipes/default.rb, recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-730
=> [HOPSWORKS-730]  Separate install and default recipies of anaconda

Karamelfile, attributes/default.rb, files/default/agent.py, files/default/csr.py, providers/keys.rb, recipes/default.rb, recipes/install.rb, templates/default/run_csr.sh.erb, templates/default/start-agent.sh.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-679
Also:
* conda-chef
* hopsworks-chef
* hops-hadoop-chef
=> [HOPSWORKS-679] Create hops-system conda environment

attributes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-811
=> [HOPSWORKS-811] Lazy Conda Environment Creation

files/default/agent.py, files/default/kagent_utils/kagent_utils/kagent_config.py, files/default/kagent_utils/tests/test_kagent_config.py, templates/default/config.ini.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-916
=> [HOPSWORKS-916] Show failure message for Conda commands

attributes/default.rb, files/default/agent.py, files/default/kagent_utils/kagent_utils/__init__.py, files/default/kagent_utils/kagent_utils/http.py, files/default/kagent_utils/kagent_utils/interval_parser.py, files/default/kagent_utils/kagent_utils/kagent_config.py, files/default/kagent_utils/kagent_utils/monitoring/host_services_watcher_action.py, files/default/kagent_utils/kagent_utils/monitoring/service.py, files/default/kagent_utils/kagent_utils/watcher.py, files/default/kagent_utils/setup.py, files/default/kagent_utils/tests/test_kagent_config.py, providers/config.rb, resources/config.rb, templates/default/status-service.sh.erb
Major refactoring of kagent
https://logicalclocks.atlassian.net/browse/HOPSWORKS-953
=> [HOPSWORKS-953] Refactor kagent monitoring system

recipes/install.rb, templates/default/restart-service.sh.erb, templates/default/shutdown-all-local-services.sh.erb, templates/default/start-all-local-services.sh.erb, templates/default/start-service.sh.erb, templates/default/status-all-local-services.sh.erb, templates/default/status-service.sh.erb, templates/default/stop-service.sh.erb, templates/default/sudoers.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-992
=> [HOPSWORKS-992]  Fix wrong command and switch to systemd commands for all scripts

attributes/default.rb
Fix incomplete refactor of hops-util-py
=> [HOPSWORKS-911] Append bugfix

files/default/agent.py
https://logicalclocks.atlassian.net/browse/HOPSWORKS-849
=> [HOPSWORKS-849]  Replay commands when kagent restarts

recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-926
=> [HOPSWORKS-926] Stringify rhel/epel attribute

recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1075
=> [HOPSWORKS-1075] Fail fast if FQDN is too long

libraries/jwt.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1033
=> [HOPSWORKS-1033] Redesign service JWT renewal protocol

templates/default/shutdown-all-local-services.sh.erb, templates/default/start-all-local-services.sh.erb, templates/default/status-all-local-services.sh.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1209
=> [HOPSWORKS-1209] Add filebeat-kagent service in startup list and move glassfish-domain1 before Hops services

libraries/default.rb, recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1247
=> [HOPSWORKS-1247] Perform some sanity checks when installing EE

files/default/agent.py, files/default/kagent_utils/kagent_utils/monitoring/service.py
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1261
=> [HOPSWORKS-1261] Add coloured logs

recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1300
=> [HOPSWORKS-1300] Replace deprecated node.set

templates/default/anaconda_env.sh.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1208
=> [HOPSWORKS-1208] JupyterLab

providers/keys.rb, recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1336
=> [HOPSWORKS-1336] Convert host private key to PKCS#1 when performing an upgrade

recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1331
=> [HOPSWORKS-1331] Consistent flag for system upgrades

providers/keys.rb, recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1336
=> [HOPSWORKS-1336] Fix bug with files ownership

libraries/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1413
=> [HOPSWORKS-1413] Do not add Authorization header if both username and password is empty

recipes/default.rb, templates/default/kagent.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1457
=> [HOPSWORKS-1457] fix systemd script

recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1474
=> [HOPSWORKS-1474] Blacklist cloud environment from kagent conda GC

files/default/csr.py, files/default/kagent_utils/kagent_utils/kagent_config.py, files/default/kagent_utils/tests/test_kagent_config.py, templates/default/config.ini.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1508
=> [HOPSWORKS-1508] Update elastic host certificate when host certificate is rotated

libraries/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1551
=> exists_local should not raise an exception if recipe is not found

files/default/csr.py, files/default/kagent_utils/kagent_utils/kagent_config.py, files/default/kagent_utils/tests/test_kagent_config.py, providers/keys.rb, templates/default/config.ini.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1549
=> [HOPSWORKS-1549] Generate Hops CA bundle on host certificate (re)generation

files/default/agent.py, files/default/csr.py, files/default/kagent_utils/kagent_utils/kagent_config.py, files/default/kagent_utils/setup.py, files/default/kagent_utils/tests/test_kagent_config.py, libraries/default.rb, providers/keys.rb, recipes/default.rb, resources/keys.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1405
=> [HOPSWORKS-1405] Use Hopsworks fqdn and change generating certificates scripts

attributes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1753
=> [HOPSWORKS-1753] Change download url

libraries/default.rb
tests: https://github.com/logicalclocks/hops-testing-ee/pull/110
=> [HOPSWORKS-1862] Fix cyclic dependency error

attributes/default.rb
tests on 1.4: https://github.com/logicalclocks/hops-testing-ee/pull/112
=> [HOPSWORKS-1871] Add admin DNs to all elasticsearch nodes

attributes/default.rb, metadata.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1904
=> [HOPSWORKS-1904] Define users group to access Hopsworks users' only certificates

attributes/default.rb, recipes/default.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-1977
=> [HOPSWORKS-1977] Replace kagent/test with kagent/enabled

templates/default/kagent.service.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
=> [HOPSWORKS-2065] Automatically restart failed systemd units

templates/default/kagent.service.erb
* [HOPSWORKS-2065] Automatically restart failed systemd units
* [HOPSWORKS-2065] Fix burst
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
[HOPSWORKS-2065]: https://logicalclocks.atlassian.net/browse/HOPSWORKS-2065
=> [HOPSWORKS-2065] Automatically restart failed systemd units (#166)

providers/keys.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2149
=> [HOPSWORKS-2149] Generate ssh key only if explicitly set

providers/keys.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2149
=> [HOPSWORKS-2149] Generate ssh key only if explicitly set (#168)

recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2182
=> [HOPSWORKS-2182] Disable unattented upgrades

recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2182
=> [HOPSWORKS-2182] Disable unattented upgrades (#170)

providers/hopsify.rb, recipes/default.rb, resources/hopsify.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2241
=> [HOPSWORKS-2241] Get Hopsworks IP only if kagent is enabled

recipes/install.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2405
=> [HOPSWORKS-2405] Change to python3

providers/config.rb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2546
=> [HOPSWORKS-2546] Do not fail when error occurs while updating services file and kagent is not enabled

attributes/default.rb, recipes/default.rb, recipes/install.rb, templates/default/config.ini.erb
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2578
=> [HOPSWORKS-2578] Create kagent etc under data dir

recipes/default.rb
Reverts logicalclocks/kagent-chef#186
=> Revert "[HOPSWORKS-2808] Fix home directory (#185)"

files/default/agent.py
https://logicalclocks.atlassian.net/browse/HOPSWORKS-2865
=> [HOPSWORKS-2865] Disallow insecure SSL/TLS protocols for kagent HTTP endpoints

providers/config.rb, resources/config.rb
Need to remove elasticsearch/kibana from the SERVICES file
=> [HOPSWORKS-2763] Upgrade to Opensearch

attributes/default.rb, recipes/install.rb
Fixes https://hopsworks.atlassian.net/browse/HOPSWORKS-3133
=> [HOPSWORKS-3133] Fix path to csr.log

attributes/default.rb, recipes/install.rb
* [HOPSWORKS-3133] Fix path to csr.log
* [HOPSWORKS-3133] Move parent directory creation
Resolves https://hopsworks.atlassian.net/browse/HOPSWORKS-3133
[HOPSWORKS-3133]: https://hopsworks.atlassian.net/browse/HOPSWORKS-3133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[HOPSWORKS-3133]: https://hopsworks.atlassian.net/browse/HOPSWORKS-3133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [HOPSWORKS-3133] Fix path to csr.log (#197)

libraries/default.rb
Resolves https://github.com/logicalclocks/hopsworks-cloud/issues/3064
=> [HOPSWORKS-CLOUD] Helper function to determine whether we are building images for the Cloud or not

providers/pki.rb
Fixes https://hopsworks.atlassian.net/browse/HWORKS-116
=> [HWORKS-116] Convert port to Integer

templates/default/dockerImageDelete.sh.erb
Fixes https://hopsworks.atlassian.net/browse/CLOUD-552
=> [CLOUD-552] Explicity add /usr/local/bin to PATH

providers/hopsify.rb, recipes/default.rb
[CLOUD-445] Remove Consul domain name from CN as this will be added as SAN
[CLOUD-445]: https://hopsworks.atlassian.net/browse/CLOUD-445?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [CLOUD-445] Renew certificates with SAN

files/default/kagent_utils/kagent_utils/monitoring/service.py
https://hopsworks.atlassian.net/browse/HWORKS-572
=> [HWORKS-572] Include uptime in kagent status-all script

recipes/default.rb
https://hopsworks.atlassian.net/browse/HWORKS-778
=> [HWORKS-778] Remove Hops CA bundle from system wide trust store and use Docker specific directory instead

recipes/default.rb
https://hopsworks.atlassian.net/browse/HWORKS-778
=> [HWORKS-779] We can't use consul_helper as it introduces a cyclic dependency

recipes/default.rb
https://hopsworks.atlassian.net/browse/HWORKS-827
=> [HWORKS-827] Create docker registry CA for both regions

recipes/default.rb
https://hopsworks.atlassian.net/browse/HWORKS-827
=> [HWORKS-827] Fix variable name

libraries/default.rb, libraries/jwt.rb
[HWORKS-743] Fix typo
[HWORKS-743]: https://hopsworks.atlassian.net/browse/HWORKS-743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [HWORKS-743] Helper function to generate API key

attributes/default.rb, metadata.rb, recipes/install.rb
https://hopsworks.atlassian.net/browse/HWORKS-889
=> [HWORKS-889] Flag to disable unattended-upgrades

files/default/agent.py, libraries/jwt.rb
https://hopsworks.atlassian.net/browse/HWORKS-992
=> [HWORKS-992] Do not use renewal tokens anylonger
